/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package runcore/ffi/runcorec */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdint.h>
 #include <stdlib.h>
typedef void (*runcore_inbound_cb)(void* user_data, const char* src_hash_hex, const char* msg_id_hex, const char* title, const char* content);
typedef void (*runcore_log_cb)(void* user_data, int32_t level, const char* line);
typedef void (*runcore_message_status_cb)(void* user_data, const char* dest_hash_hex, const char* msg_id_hex, int32_t state);

static inline void runcore_inbound_cb_call(runcore_inbound_cb cb, void* user_data, const char* src, const char* msg_id, const char* title, const char* content) {
  cb(user_data, src, msg_id, title, content);
}
static inline void runcore_log_cb_call(runcore_log_cb cb, void* user_data, int32_t level, const char* line) {
  cb(user_data, level, line);
}
static inline void runcore_message_status_cb_call(runcore_message_status_cb cb, void* user_data, const char* dest, const char* msg_id, int32_t state) {
  cb(user_data, dest, msg_id, state);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void runcore_free_string(char* p);
extern char* runcore_default_lxmd_config(void);
extern char* runcore_default_lxmd_config_for_name(char* displayName);
extern char* runcore_default_rns_config(int32_t loglevel);
extern uint64_t runcore_start(char* configDir, char* displayName, int32_t loglevel, int32_t resetLXMF);
extern int32_t runcore_stop(uint64_t handle);
extern void runcore_set_inbound_cb(uint64_t handle, runcore_inbound_cb cb, void* userData);
extern void runcore_set_message_status_cb(uint64_t handle, runcore_message_status_cb cb, void* userData);
extern void runcore_set_log_cb(runcore_log_cb cb, void* userData);
extern void runcore_set_loglevel(int32_t level);
extern char* runcore_destination_hash_hex(uint64_t handle);
extern int32_t runcore_send(uint64_t handle, char* destHashHex, char* title, char* content);
extern char* runcore_send_result_json(uint64_t handle, char* destHashHex, char* title, char* content);
extern int32_t runcore_announce(uint64_t handle);
extern int32_t runcore_announce_with_reason(uint64_t handle, char* reason);
extern int32_t runcore_set_display_name(uint64_t handle, char* displayName);
extern int32_t runcore_restart(uint64_t handle);
extern char* runcore_interface_stats_json(uint64_t handle);
extern char* runcore_configured_interfaces_json(uint64_t handle);
extern char* runcore_announces_json(uint64_t handle);
extern char* runcore_contact_info_json(uint64_t handle, char* destHashHex, int32_t timeoutMs);
extern char* runcore_contact_avatar_json(uint64_t handle, char* destHashHex, char* knownAvatarHashHex, int32_t timeoutMs);
extern char* runcore_store_attachment_json(uint64_t handle, char* mime, char* name, unsigned char* data, int32_t dataLen);
extern char* runcore_contact_attachment_json(uint64_t handle, char* destHashHex, char* attachmentHashHex, int32_t timeoutMs);
extern int32_t runcore_set_avatar_png(uint64_t handle, unsigned char* pngData, int32_t pngLen);
extern int32_t runcore_set_avatar_image(uint64_t handle, char* mime, unsigned char* data, int32_t dataLen);
extern int32_t runcore_clear_avatar(uint64_t handle);
extern int32_t runcore_set_interface_enabled(uint64_t handle, char* name, int32_t enabled);

#ifdef __cplusplus
}
#endif
